import { createFileRoute, Link } from '@tanstack/react-router';

// This file is auto-generated by ds-imports/route-index-generator.js
// Do not edit this file directly!

export const Route = createFileRoute('/')({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <div className="dsr-routes">
      <Link to="/klublotto" className="dsr-routes__link dsr-routes__link--main">
        Klublotto
      </Link>
    </div>
  );
}
