import { createFileRoute, Link } from '@tanstack/react-router'

// This file is auto-generated by ds-imports/route-index-generator.js
// Do not edit this file directly!

export const Route = createFileRoute('/quick/')({
  component: RouteComponent,
})

function RouteComponent() {
  return <div className="dsr-routes">
<Link className="dsr-routes__link dsr-routes__link--back" to="/">&larr;&nbsp; Back</Link><Link className="dsr-routes__link" to="/quick/Frontpage">Frontpage</Link>
<Link className="dsr-routes__link" to="/quick/HeroDeckSliderSpot">HeroDeckSliderSpot</Link>
<Link className="dsr-routes__link" to="/quick/SliderSpot">SliderSpot</Link>
  </div>
}
