import { createFileRoute, Link } from '@tanstack/react-router';

// This file is auto-generated by ds-imports/route-index-generator.js
// Do not edit this file directly!

export const Route = createFileRoute('/klublotto/')({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <div className="dsr-routes">
      <Link className="dsr-routes__link dsr-routes__link--back" to="/">
        &larr;&nbsp; Back
      </Link>
      <Link className="dsr-routes__link" to="/klublotto/Countdown">
        Countdown
      </Link>
      <Link className="dsr-routes__link" to="/klublotto/LottoRowClaim-Receipt">
        LottoRowClaim Receipt
      </Link>
      <Link className="dsr-routes__link" to="/klublotto/NewsSlider">
        NewsSlider
      </Link>
      <Link className="dsr-routes__link" to="/klublotto/Popups">
        Popups
      </Link>
      <Link className="dsr-routes__link" to="/klublotto/StarStep">
        StarStep
      </Link>
      <Link className="dsr-routes__link" to="/klublotto/TitleBase">
        TitleBase
      </Link>
    </div>
  );
}
