import { createFileRoute, Link } from '@tanstack/react-router'

// This file is auto-generated by ds-imports/route-index-generator.js
// Do not edit this file directly!

export const Route = createFileRoute('/klublotto/')({
  component: RouteComponent,
})

function RouteComponent() {
  return <div className="dsr-routes">
<Link className="dsr-routes__link dsr-routes__link--back" to="/">&larr;&nbsp; Back</Link><Link className="dsr-routes__link" to="/klublotto/DailyPlayHub">DailyPlayHub</Link>
<Link className="dsr-routes__link" to="/klublotto/FreePrizeClaim-Claim">FreePrizeClaim Claim</Link>
<Link className="dsr-routes__link" to="/klublotto/FreePrizeClaim">FreePrizeClaim</Link>
<Link className="dsr-routes__link" to="/klublotto/FreePrizeClaimReceipt">FreePrizeClaimReceipt</Link>
<Link className="dsr-routes__link" to="/klublotto/MyRewards">MyRewards</Link>
<Link className="dsr-routes__link" to="/klublotto/PromotionBanner">PromotionBanner</Link>
<Link className="dsr-routes__link" to="/klublotto/Title">Title</Link>
  </div>
}
