/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlublottoIndexRouteImport } from './routes/klublotto/index'
import { Route as KlublottoFreePrizeClaimReceiptRouteImport } from './routes/klublotto/FreePrizeClaimReceipt'
import { Route as KlublottoFreePrizeClaimClaimRouteImport } from './routes/klublotto/FreePrizeClaim-Claim'
import { Route as KlublottoFreePrizeClaimRouteImport } from './routes/klublotto/FreePrizeClaim'
import { Route as KlublottoDailyPlayHubRouteImport } from './routes/klublotto/DailyPlayHub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoIndexRoute = KlublottoIndexRouteImport.update({
  id: '/klublotto/',
  path: '/klublotto/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoFreePrizeClaimReceiptRoute =
  KlublottoFreePrizeClaimReceiptRouteImport.update({
    id: '/klublotto/FreePrizeClaimReceipt',
    path: '/klublotto/FreePrizeClaimReceipt',
    getParentRoute: () => rootRouteImport,
  } as any)
const KlublottoFreePrizeClaimClaimRoute =
  KlublottoFreePrizeClaimClaimRouteImport.update({
    id: '/klublotto/FreePrizeClaim-Claim',
    path: '/klublotto/FreePrizeClaim-Claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const KlublottoFreePrizeClaimRoute = KlublottoFreePrizeClaimRouteImport.update({
  id: '/klublotto/FreePrizeClaim',
  path: '/klublotto/FreePrizeClaim',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoDailyPlayHubRoute = KlublottoDailyPlayHubRouteImport.update({
  id: '/klublotto/DailyPlayHub',
  path: '/klublotto/DailyPlayHub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/klublotto/DailyPlayHub': typeof KlublottoDailyPlayHubRoute
  '/klublotto/FreePrizeClaim': typeof KlublottoFreePrizeClaimRoute
  '/klublotto/FreePrizeClaim-Claim': typeof KlublottoFreePrizeClaimClaimRoute
  '/klublotto/FreePrizeClaimReceipt': typeof KlublottoFreePrizeClaimReceiptRoute
  '/klublotto': typeof KlublottoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/klublotto/DailyPlayHub': typeof KlublottoDailyPlayHubRoute
  '/klublotto/FreePrizeClaim': typeof KlublottoFreePrizeClaimRoute
  '/klublotto/FreePrizeClaim-Claim': typeof KlublottoFreePrizeClaimClaimRoute
  '/klublotto/FreePrizeClaimReceipt': typeof KlublottoFreePrizeClaimReceiptRoute
  '/klublotto': typeof KlublottoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/klublotto/DailyPlayHub': typeof KlublottoDailyPlayHubRoute
  '/klublotto/FreePrizeClaim': typeof KlublottoFreePrizeClaimRoute
  '/klublotto/FreePrizeClaim-Claim': typeof KlublottoFreePrizeClaimClaimRoute
  '/klublotto/FreePrizeClaimReceipt': typeof KlublottoFreePrizeClaimReceiptRoute
  '/klublotto/': typeof KlublottoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/klublotto/DailyPlayHub'
    | '/klublotto/FreePrizeClaim'
    | '/klublotto/FreePrizeClaim-Claim'
    | '/klublotto/FreePrizeClaimReceipt'
    | '/klublotto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/klublotto/DailyPlayHub'
    | '/klublotto/FreePrizeClaim'
    | '/klublotto/FreePrizeClaim-Claim'
    | '/klublotto/FreePrizeClaimReceipt'
    | '/klublotto'
  id:
    | '__root__'
    | '/'
    | '/klublotto/DailyPlayHub'
    | '/klublotto/FreePrizeClaim'
    | '/klublotto/FreePrizeClaim-Claim'
    | '/klublotto/FreePrizeClaimReceipt'
    | '/klublotto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KlublottoDailyPlayHubRoute: typeof KlublottoDailyPlayHubRoute
  KlublottoFreePrizeClaimRoute: typeof KlublottoFreePrizeClaimRoute
  KlublottoFreePrizeClaimClaimRoute: typeof KlublottoFreePrizeClaimClaimRoute
  KlublottoFreePrizeClaimReceiptRoute: typeof KlublottoFreePrizeClaimReceiptRoute
  KlublottoIndexRoute: typeof KlublottoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/': {
      id: '/klublotto/'
      path: '/klublotto'
      fullPath: '/klublotto'
      preLoaderRoute: typeof KlublottoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/FreePrizeClaimReceipt': {
      id: '/klublotto/FreePrizeClaimReceipt'
      path: '/klublotto/FreePrizeClaimReceipt'
      fullPath: '/klublotto/FreePrizeClaimReceipt'
      preLoaderRoute: typeof KlublottoFreePrizeClaimReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/FreePrizeClaim-Claim': {
      id: '/klublotto/FreePrizeClaim-Claim'
      path: '/klublotto/FreePrizeClaim-Claim'
      fullPath: '/klublotto/FreePrizeClaim-Claim'
      preLoaderRoute: typeof KlublottoFreePrizeClaimClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/FreePrizeClaim': {
      id: '/klublotto/FreePrizeClaim'
      path: '/klublotto/FreePrizeClaim'
      fullPath: '/klublotto/FreePrizeClaim'
      preLoaderRoute: typeof KlublottoFreePrizeClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/DailyPlayHub': {
      id: '/klublotto/DailyPlayHub'
      path: '/klublotto/DailyPlayHub'
      fullPath: '/klublotto/DailyPlayHub'
      preLoaderRoute: typeof KlublottoDailyPlayHubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KlublottoDailyPlayHubRoute: KlublottoDailyPlayHubRoute,
  KlublottoFreePrizeClaimRoute: KlublottoFreePrizeClaimRoute,
  KlublottoFreePrizeClaimClaimRoute: KlublottoFreePrizeClaimClaimRoute,
  KlublottoFreePrizeClaimReceiptRoute: KlublottoFreePrizeClaimReceiptRoute,
  KlublottoIndexRoute: KlublottoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
