/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as KlublottoIndexImport } from './routes/klublotto/index';
import { Route as KlublottoTitleBaseImport } from './routes/klublotto/title-base';
import { Route as KlublottoStarstepImport } from './routes/klublotto/starstep';
import { Route as KlublottoPopupsImport } from './routes/klublotto/popups';
import { Route as KlublottoCountdownImport } from './routes/klublotto/countdown';
import { Route as KlublottoNewsSliderImport } from './routes/klublotto/NewsSlider';
import { Route as KlublottoLottoRowClaimReceiptImport } from './routes/klublotto/LottoRowClaim-Receipt';

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const KlublottoIndexRoute = KlublottoIndexImport.update({
  id: '/klublotto/',
  path: '/klublotto/',
  getParentRoute: () => rootRoute,
} as any);

const KlublottoTitleBaseRoute = KlublottoTitleBaseImport.update({
  id: '/klublotto/title-base',
  path: '/klublotto/title-base',
  getParentRoute: () => rootRoute,
} as any);

const KlublottoStarstepRoute = KlublottoStarstepImport.update({
  id: '/klublotto/starstep',
  path: '/klublotto/starstep',
  getParentRoute: () => rootRoute,
} as any);

const KlublottoPopupsRoute = KlublottoPopupsImport.update({
  id: '/klublotto/popups',
  path: '/klublotto/popups',
  getParentRoute: () => rootRoute,
} as any);

const KlublottoCountdownRoute = KlublottoCountdownImport.update({
  id: '/klublotto/countdown',
  path: '/klublotto/countdown',
  getParentRoute: () => rootRoute,
} as any);

const KlublottoNewsSliderRoute = KlublottoNewsSliderImport.update({
  id: '/klublotto/NewsSlider',
  path: '/klublotto/NewsSlider',
  getParentRoute: () => rootRoute,
} as any);

const KlublottoLottoRowClaimReceiptRoute = KlublottoLottoRowClaimReceiptImport.update({
  id: '/klublotto/LottoRowClaim-Receipt',
  path: '/klublotto/LottoRowClaim-Receipt',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/klublotto/LottoRowClaim-Receipt': {
      id: '/klublotto/LottoRowClaim-Receipt';
      path: '/klublotto/LottoRowClaim-Receipt';
      fullPath: '/klublotto/LottoRowClaim-Receipt';
      preLoaderRoute: typeof KlublottoLottoRowClaimReceiptImport;
      parentRoute: typeof rootRoute;
    };
    '/klublotto/NewsSlider': {
      id: '/klublotto/NewsSlider';
      path: '/klublotto/NewsSlider';
      fullPath: '/klublotto/NewsSlider';
      preLoaderRoute: typeof KlublottoNewsSliderImport;
      parentRoute: typeof rootRoute;
    };
    '/klublotto/countdown': {
      id: '/klublotto/countdown';
      path: '/klublotto/countdown';
      fullPath: '/klublotto/countdown';
      preLoaderRoute: typeof KlublottoCountdownImport;
      parentRoute: typeof rootRoute;
    };
    '/klublotto/popups': {
      id: '/klublotto/popups';
      path: '/klublotto/popups';
      fullPath: '/klublotto/popups';
      preLoaderRoute: typeof KlublottoPopupsImport;
      parentRoute: typeof rootRoute;
    };
    '/klublotto/starstep': {
      id: '/klublotto/starstep';
      path: '/klublotto/starstep';
      fullPath: '/klublotto/starstep';
      preLoaderRoute: typeof KlublottoStarstepImport;
      parentRoute: typeof rootRoute;
    };
    '/klublotto/title-base': {
      id: '/klublotto/title-base';
      path: '/klublotto/title-base';
      fullPath: '/klublotto/title-base';
      preLoaderRoute: typeof KlublottoTitleBaseImport;
      parentRoute: typeof rootRoute;
    };
    '/klublotto/': {
      id: '/klublotto/';
      path: '/klublotto';
      fullPath: '/klublotto';
      preLoaderRoute: typeof KlublottoIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/klublotto/LottoRowClaim-Receipt': typeof KlublottoLottoRowClaimReceiptRoute;
  '/klublotto/NewsSlider': typeof KlublottoNewsSliderRoute;
  '/klublotto/countdown': typeof KlublottoCountdownRoute;
  '/klublotto/popups': typeof KlublottoPopupsRoute;
  '/klublotto/starstep': typeof KlublottoStarstepRoute;
  '/klublotto/title-base': typeof KlublottoTitleBaseRoute;
  '/klublotto': typeof KlublottoIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/klublotto/LottoRowClaim-Receipt': typeof KlublottoLottoRowClaimReceiptRoute;
  '/klublotto/NewsSlider': typeof KlublottoNewsSliderRoute;
  '/klublotto/countdown': typeof KlublottoCountdownRoute;
  '/klublotto/popups': typeof KlublottoPopupsRoute;
  '/klublotto/starstep': typeof KlublottoStarstepRoute;
  '/klublotto/title-base': typeof KlublottoTitleBaseRoute;
  '/klublotto': typeof KlublottoIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/klublotto/LottoRowClaim-Receipt': typeof KlublottoLottoRowClaimReceiptRoute;
  '/klublotto/NewsSlider': typeof KlublottoNewsSliderRoute;
  '/klublotto/countdown': typeof KlublottoCountdownRoute;
  '/klublotto/popups': typeof KlublottoPopupsRoute;
  '/klublotto/starstep': typeof KlublottoStarstepRoute;
  '/klublotto/title-base': typeof KlublottoTitleBaseRoute;
  '/klublotto/': typeof KlublottoIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/klublotto/LottoRowClaim-Receipt'
    | '/klublotto/NewsSlider'
    | '/klublotto/countdown'
    | '/klublotto/popups'
    | '/klublotto/starstep'
    | '/klublotto/title-base'
    | '/klublotto';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/klublotto/LottoRowClaim-Receipt'
    | '/klublotto/NewsSlider'
    | '/klublotto/countdown'
    | '/klublotto/popups'
    | '/klublotto/starstep'
    | '/klublotto/title-base'
    | '/klublotto';
  id:
    | '__root__'
    | '/'
    | '/klublotto/LottoRowClaim-Receipt'
    | '/klublotto/NewsSlider'
    | '/klublotto/countdown'
    | '/klublotto/popups'
    | '/klublotto/starstep'
    | '/klublotto/title-base'
    | '/klublotto/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  KlublottoLottoRowClaimReceiptRoute: typeof KlublottoLottoRowClaimReceiptRoute;
  KlublottoNewsSliderRoute: typeof KlublottoNewsSliderRoute;
  KlublottoCountdownRoute: typeof KlublottoCountdownRoute;
  KlublottoPopupsRoute: typeof KlublottoPopupsRoute;
  KlublottoStarstepRoute: typeof KlublottoStarstepRoute;
  KlublottoTitleBaseRoute: typeof KlublottoTitleBaseRoute;
  KlublottoIndexRoute: typeof KlublottoIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KlublottoLottoRowClaimReceiptRoute: KlublottoLottoRowClaimReceiptRoute,
  KlublottoNewsSliderRoute: KlublottoNewsSliderRoute,
  KlublottoCountdownRoute: KlublottoCountdownRoute,
  KlublottoPopupsRoute: KlublottoPopupsRoute,
  KlublottoStarstepRoute: KlublottoStarstepRoute,
  KlublottoTitleBaseRoute: KlublottoTitleBaseRoute,
  KlublottoIndexRoute: KlublottoIndexRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/klublotto/LottoRowClaim-Receipt",
        "/klublotto/NewsSlider",
        "/klublotto/countdown",
        "/klublotto/popups",
        "/klublotto/starstep",
        "/klublotto/title-base",
        "/klublotto/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/klublotto/LottoRowClaim-Receipt": {
      "filePath": "klublotto/LottoRowClaim-Receipt.tsx"
    },
    "/klublotto/NewsSlider": {
      "filePath": "klublotto/NewsSlider.tsx"
    },
    "/klublotto/countdown": {
      "filePath": "klublotto/countdown.tsx"
    },
    "/klublotto/popups": {
      "filePath": "klublotto/popups.tsx"
    },
    "/klublotto/starstep": {
      "filePath": "klublotto/starstep.tsx"
    },
    "/klublotto/title-base": {
      "filePath": "klublotto/title-base.tsx"
    },
    "/klublotto/": {
      "filePath": "klublotto/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
