/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KlublottoIndexRouteImport } from './routes/klublotto/index'
import { Route as KlublottoTitleRouteImport } from './routes/klublotto/Title'
import { Route as KlublottoPromotionBannerRouteImport } from './routes/klublotto/PromotionBanner'
import { Route as KlublottoNewPrizeNotificationRouteImport } from './routes/klublotto/NewPrizeNotification'
import { Route as KlublottoMyRewardsRouteImport } from './routes/klublotto/MyRewards'
import { Route as KlublottoFreePrizeClaimReceiptRouteImport } from './routes/klublotto/FreePrizeClaimReceipt'
import { Route as KlublottoFreePrizeClaimClaimRouteImport } from './routes/klublotto/FreePrizeClaim-Claim'
import { Route as KlublottoFreePrizeClaimRouteImport } from './routes/klublotto/FreePrizeClaim'
import { Route as KlublottoDailyPlayHubRouteImport } from './routes/klublotto/DailyPlayHub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoIndexRoute = KlublottoIndexRouteImport.update({
  id: '/klublotto/',
  path: '/klublotto/',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoTitleRoute = KlublottoTitleRouteImport.update({
  id: '/klublotto/Title',
  path: '/klublotto/Title',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoPromotionBannerRoute =
  KlublottoPromotionBannerRouteImport.update({
    id: '/klublotto/PromotionBanner',
    path: '/klublotto/PromotionBanner',
    getParentRoute: () => rootRouteImport,
  } as any)
const KlublottoNewPrizeNotificationRoute =
  KlublottoNewPrizeNotificationRouteImport.update({
    id: '/klublotto/NewPrizeNotification',
    path: '/klublotto/NewPrizeNotification',
    getParentRoute: () => rootRouteImport,
  } as any)
const KlublottoMyRewardsRoute = KlublottoMyRewardsRouteImport.update({
  id: '/klublotto/MyRewards',
  path: '/klublotto/MyRewards',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoFreePrizeClaimReceiptRoute =
  KlublottoFreePrizeClaimReceiptRouteImport.update({
    id: '/klublotto/FreePrizeClaimReceipt',
    path: '/klublotto/FreePrizeClaimReceipt',
    getParentRoute: () => rootRouteImport,
  } as any)
const KlublottoFreePrizeClaimClaimRoute =
  KlublottoFreePrizeClaimClaimRouteImport.update({
    id: '/klublotto/FreePrizeClaim-Claim',
    path: '/klublotto/FreePrizeClaim-Claim',
    getParentRoute: () => rootRouteImport,
  } as any)
const KlublottoFreePrizeClaimRoute = KlublottoFreePrizeClaimRouteImport.update({
  id: '/klublotto/FreePrizeClaim',
  path: '/klublotto/FreePrizeClaim',
  getParentRoute: () => rootRouteImport,
} as any)
const KlublottoDailyPlayHubRoute = KlublottoDailyPlayHubRouteImport.update({
  id: '/klublotto/DailyPlayHub',
  path: '/klublotto/DailyPlayHub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/klublotto/DailyPlayHub': typeof KlublottoDailyPlayHubRoute
  '/klublotto/FreePrizeClaim': typeof KlublottoFreePrizeClaimRoute
  '/klublotto/FreePrizeClaim-Claim': typeof KlublottoFreePrizeClaimClaimRoute
  '/klublotto/FreePrizeClaimReceipt': typeof KlublottoFreePrizeClaimReceiptRoute
  '/klublotto/MyRewards': typeof KlublottoMyRewardsRoute
  '/klublotto/NewPrizeNotification': typeof KlublottoNewPrizeNotificationRoute
  '/klublotto/PromotionBanner': typeof KlublottoPromotionBannerRoute
  '/klublotto/Title': typeof KlublottoTitleRoute
  '/klublotto': typeof KlublottoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/klublotto/DailyPlayHub': typeof KlublottoDailyPlayHubRoute
  '/klublotto/FreePrizeClaim': typeof KlublottoFreePrizeClaimRoute
  '/klublotto/FreePrizeClaim-Claim': typeof KlublottoFreePrizeClaimClaimRoute
  '/klublotto/FreePrizeClaimReceipt': typeof KlublottoFreePrizeClaimReceiptRoute
  '/klublotto/MyRewards': typeof KlublottoMyRewardsRoute
  '/klublotto/NewPrizeNotification': typeof KlublottoNewPrizeNotificationRoute
  '/klublotto/PromotionBanner': typeof KlublottoPromotionBannerRoute
  '/klublotto/Title': typeof KlublottoTitleRoute
  '/klublotto': typeof KlublottoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/klublotto/DailyPlayHub': typeof KlublottoDailyPlayHubRoute
  '/klublotto/FreePrizeClaim': typeof KlublottoFreePrizeClaimRoute
  '/klublotto/FreePrizeClaim-Claim': typeof KlublottoFreePrizeClaimClaimRoute
  '/klublotto/FreePrizeClaimReceipt': typeof KlublottoFreePrizeClaimReceiptRoute
  '/klublotto/MyRewards': typeof KlublottoMyRewardsRoute
  '/klublotto/NewPrizeNotification': typeof KlublottoNewPrizeNotificationRoute
  '/klublotto/PromotionBanner': typeof KlublottoPromotionBannerRoute
  '/klublotto/Title': typeof KlublottoTitleRoute
  '/klublotto/': typeof KlublottoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/klublotto/DailyPlayHub'
    | '/klublotto/FreePrizeClaim'
    | '/klublotto/FreePrizeClaim-Claim'
    | '/klublotto/FreePrizeClaimReceipt'
    | '/klublotto/MyRewards'
    | '/klublotto/NewPrizeNotification'
    | '/klublotto/PromotionBanner'
    | '/klublotto/Title'
    | '/klublotto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/klublotto/DailyPlayHub'
    | '/klublotto/FreePrizeClaim'
    | '/klublotto/FreePrizeClaim-Claim'
    | '/klublotto/FreePrizeClaimReceipt'
    | '/klublotto/MyRewards'
    | '/klublotto/NewPrizeNotification'
    | '/klublotto/PromotionBanner'
    | '/klublotto/Title'
    | '/klublotto'
  id:
    | '__root__'
    | '/'
    | '/klublotto/DailyPlayHub'
    | '/klublotto/FreePrizeClaim'
    | '/klublotto/FreePrizeClaim-Claim'
    | '/klublotto/FreePrizeClaimReceipt'
    | '/klublotto/MyRewards'
    | '/klublotto/NewPrizeNotification'
    | '/klublotto/PromotionBanner'
    | '/klublotto/Title'
    | '/klublotto/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KlublottoDailyPlayHubRoute: typeof KlublottoDailyPlayHubRoute
  KlublottoFreePrizeClaimRoute: typeof KlublottoFreePrizeClaimRoute
  KlublottoFreePrizeClaimClaimRoute: typeof KlublottoFreePrizeClaimClaimRoute
  KlublottoFreePrizeClaimReceiptRoute: typeof KlublottoFreePrizeClaimReceiptRoute
  KlublottoMyRewardsRoute: typeof KlublottoMyRewardsRoute
  KlublottoNewPrizeNotificationRoute: typeof KlublottoNewPrizeNotificationRoute
  KlublottoPromotionBannerRoute: typeof KlublottoPromotionBannerRoute
  KlublottoTitleRoute: typeof KlublottoTitleRoute
  KlublottoIndexRoute: typeof KlublottoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/': {
      id: '/klublotto/'
      path: '/klublotto'
      fullPath: '/klublotto'
      preLoaderRoute: typeof KlublottoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/Title': {
      id: '/klublotto/Title'
      path: '/klublotto/Title'
      fullPath: '/klublotto/Title'
      preLoaderRoute: typeof KlublottoTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/PromotionBanner': {
      id: '/klublotto/PromotionBanner'
      path: '/klublotto/PromotionBanner'
      fullPath: '/klublotto/PromotionBanner'
      preLoaderRoute: typeof KlublottoPromotionBannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/NewPrizeNotification': {
      id: '/klublotto/NewPrizeNotification'
      path: '/klublotto/NewPrizeNotification'
      fullPath: '/klublotto/NewPrizeNotification'
      preLoaderRoute: typeof KlublottoNewPrizeNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/MyRewards': {
      id: '/klublotto/MyRewards'
      path: '/klublotto/MyRewards'
      fullPath: '/klublotto/MyRewards'
      preLoaderRoute: typeof KlublottoMyRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/FreePrizeClaimReceipt': {
      id: '/klublotto/FreePrizeClaimReceipt'
      path: '/klublotto/FreePrizeClaimReceipt'
      fullPath: '/klublotto/FreePrizeClaimReceipt'
      preLoaderRoute: typeof KlublottoFreePrizeClaimReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/FreePrizeClaim-Claim': {
      id: '/klublotto/FreePrizeClaim-Claim'
      path: '/klublotto/FreePrizeClaim-Claim'
      fullPath: '/klublotto/FreePrizeClaim-Claim'
      preLoaderRoute: typeof KlublottoFreePrizeClaimClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/FreePrizeClaim': {
      id: '/klublotto/FreePrizeClaim'
      path: '/klublotto/FreePrizeClaim'
      fullPath: '/klublotto/FreePrizeClaim'
      preLoaderRoute: typeof KlublottoFreePrizeClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klublotto/DailyPlayHub': {
      id: '/klublotto/DailyPlayHub'
      path: '/klublotto/DailyPlayHub'
      fullPath: '/klublotto/DailyPlayHub'
      preLoaderRoute: typeof KlublottoDailyPlayHubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KlublottoDailyPlayHubRoute: KlublottoDailyPlayHubRoute,
  KlublottoFreePrizeClaimRoute: KlublottoFreePrizeClaimRoute,
  KlublottoFreePrizeClaimClaimRoute: KlublottoFreePrizeClaimClaimRoute,
  KlublottoFreePrizeClaimReceiptRoute: KlublottoFreePrizeClaimReceiptRoute,
  KlublottoMyRewardsRoute: KlublottoMyRewardsRoute,
  KlublottoNewPrizeNotificationRoute: KlublottoNewPrizeNotificationRoute,
  KlublottoPromotionBannerRoute: KlublottoPromotionBannerRoute,
  KlublottoTitleRoute: KlublottoTitleRoute,
  KlublottoIndexRoute: KlublottoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
